version: '3'
services:
    nginx:
        build:
            context: ./.docker
            dockerfile: nginx.docker
        container_name: messenger-nginx
        volumes:
            - ./:/var/www
        ports:
            - "8080:443"
        links:
            - php-fpm
    php-fpm:
        build:
            context: ./.docker
            dockerfile: php-fpm.docker
        container_name: messenger-php-fpm
        volumes:
            - ./:/var/www
        links:
            - redis
        environment:
            - "REDIS_PORT=6379"
            - "REDIS_HOST=redis"
    redis:
        image: redis:3.2.10
        container_name: messenger-redis
        ports:
            - "63791:6379"

volumes:
    data: {}
